/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengelolawaralaba;

/**
 *
 * @author user
 */
public class memberProfil extends javax.swing.JFrame {

    /**
     * Creates new form memberProfil
     */
    public memberProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        profilBtn = new javax.swing.JButton();
        produkBtn = new javax.swing.JButton();
        riwayatBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengelolawaralaba/gambar/member profil.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1490, 790));

        profilBtn.setText("jButton1");
        profilBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilBtnMouseClicked(evt);
            }
        });
        profilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilBtnActionPerformed(evt);
            }
        });
        getContentPane().add(profilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 90, 20));

        produkBtn.setText("jButton2");
        produkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkBtnMouseClicked(evt);
            }
        });
        produkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkBtnActionPerformed(evt);
            }
        });
        getContentPane().add(produkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 90, 20));

        riwayatBtn.setText("jButton3");
        riwayatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatBtnMouseClicked(evt);
            }
        });
        riwayatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(riwayatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilBtnActionPerformed

    private void produkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkBtnActionPerformed
        
    }//GEN-LAST:event_produkBtnActionPerformed

    private void riwayatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatBtnActionPerformed
        
    }//GEN-LAST:event_riwayatBtnActionPerformed

    private void profilBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilBtnMouseClicked

    private void produkBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkBtnMouseClicked
        memberProduk produkBtn = new memberProduk();
        produkBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_produkBtnMouseClicked

    private void riwayatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatBtnMouseClicked
        memberRiwayat riwayatBtn = new memberRiwayat();
        riwayatBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_riwayatBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memberProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton produkBtn;
    private javax.swing.JButton profilBtn;
    private javax.swing.JButton riwayatBtn;
    // End of variables declaration//GEN-END:variables
}
